const p1 = require("../picture/place/1.png")
const p2 = require("../picture/place/2.png")
const p3 = require("../picture/place/3.png")
const p4 = require("../picture/place/4.png")
const p5 = require("../picture/place/5.png")
const p6 = require("../picture/place/6.png")
const p7 = require("../picture/place/7.png")
const p8 = require("../picture/place/8.png")
const p9 = require("../picture/place/9.png")
const p10 = require("../picture/place/10.png")
const p11 = require("../picture/place/11.png")
const p12 = require("../picture/place/12.png")
const p13 = require("../picture/place/13.png")
const p14 = require("../picture/place/14.png")
const p15 = require("../picture/place/15.png")
const p16 = require("../picture/place/16.png")
const p17 = require("../picture/place/17.png")
const p18 = require("../picture/place/18.png")
const p19 = require("../picture/place/19.png")
const p20 = require("../picture/place/20.png")
const p21 = require("../picture/place/21.png")
const p22 = require("../picture/place/22.png")
const p23 = require("../picture/place/23.png")
const p24 = require("../picture/place/24.png")
const p25 = require("../picture/place/25.png")
const p26 = require("../picture/place/26.png")
const p27 = require("../picture/place/27.png")
const p28 = require("../picture/place/28.png")
const p29 = require("../picture/place/29.png")
const p30 = require("../picture/place/30.png")
const Place = [p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,
        p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30]


export default Place